name: Run unit tests

on:
  push

env:
  GO_VERSION: 1.22

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        # Run up to 3 times in case there is a flaky test
        run: |
          retry() {
            local n=0
            until [ "$n" -ge 3 ]
            do
              go test -v -race ./... && break
              n=$((n+1))
              echo "Retry #$n..."
            done
          }
          retry
